"""
COLMAP-backed reconstruction helpers.

This uses COLMAP for real structure-from-motion when the command-line tool is
available in the deployment image, then exports a sparse colored point model
that the existing viewer can load as GLB.
"""

import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Callable

import cv2
import numpy as np
import trimesh


def is_colmap_available() -> bool:
    return shutil.which("colmap") is not None


def _run_colmap(args: list[str], workdir: Path, timeout: int = 900):
    env = os.environ.copy()
    env.setdefault("QT_QPA_PLATFORM", "offscreen")

    completed = subprocess.run(
        ["colmap", *args],
        cwd=workdir,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=timeout,
        check=False,
    )

    if completed.returncode != 0:
        output = completed.stdout[-4000:] if completed.stdout else ""
        raise RuntimeError(f"COLMAP {' '.join(args[:1])} failed: {output}")


def _write_images(image_bytes_list: list[bytes], image_dir: Path, quality: int) -> int:
    image_dir.mkdir(parents=True, exist_ok=True)
    max_dim = 2200 if quality >= 85 else 1600
    written = 0

    for index, raw in enumerate(image_bytes_list):
        arr = np.frombuffer(raw, np.uint8)
        img = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        if img is None:
            continue

        h, w = img.shape[:2]
        if max(h, w) > max_dim:
            scale = max_dim / max(h, w)
            img = cv2.resize(img, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)

        path = image_dir / f"image_{index:04d}.jpg"
        cv2.imwrite(str(path), img, [int(cv2.IMWRITE_JPEG_QUALITY), 94])
        written += 1

    return written


def _load_ply_as_arrays(ply_path: Path) -> tuple[np.ndarray, np.ndarray]:
    cloud = trimesh.load(str(ply_path), process=False)

    if isinstance(cloud, trimesh.Scene):
        geometries = [geom for geom in cloud.geometry.values() if hasattr(geom, "vertices")]
        if not geometries:
            return np.zeros((0, 3)), np.zeros((0, 3), dtype=np.uint8)
        cloud = geometries[0]

    points = np.asarray(getattr(cloud, "vertices", []), dtype=np.float64)
    if points.size == 0:
        return np.zeros((0, 3)), np.zeros((0, 3), dtype=np.uint8)

    colors = getattr(getattr(cloud, "visual", None), "vertex_colors", None)
    if colors is None or len(colors) != len(points):
        colors = np.full((len(points), 3), 210, dtype=np.uint8)
    else:
        colors = np.asarray(colors, dtype=np.uint8)[:, :3]

    return points, colors


def _export_glb_points(points: np.ndarray, colors: np.ndarray) -> bytes | None:
    if len(points) == 0:
        return None

    if len(points) > 120_000:
        indices = np.linspace(0, len(points) - 1, 120_000, dtype=np.int64)
        points = points[indices]
        colors = colors[indices]

    cloud = trimesh.PointCloud(vertices=points, colors=colors)
    exported = cloud.export(file_type="glb")
    return exported if isinstance(exported, bytes) else bytes(exported)


def _export_obj_points(points: np.ndarray, colors: np.ndarray, scan_name: str) -> bytes:
    lines = [f"# {scan_name}", "# Generated by Visionaire COLMAP pipeline", f"# Points: {len(points)}"]
    normalized = np.clip(colors.astype(np.float64) / 255.0, 0, 1)

    for point, color in zip(points, normalized):
        lines.append(
            f"v {point[0]:.6f} {point[1]:.6f} {point[2]:.6f} "
            f"{color[0]:.4f} {color[1]:.4f} {color[2]:.4f}"
        )

    return "\n".join(lines).encode("utf-8")


def reconstruct_with_colmap(
    image_bytes_list: list[bytes],
    quality: int = 78,
    detail: int = 64,
    scan_name: str = "Visionaire Model",
    on_progress: Callable | None = None,
) -> dict:
    with tempfile.TemporaryDirectory(prefix="visionaire_colmap_") as tmp:
        workdir = Path(tmp)
        image_dir = workdir / "images"
        sparse_dir = workdir / "sparse"
        sparse_dir.mkdir()

        image_count = _write_images(image_bytes_list, image_dir, quality)
        if image_count < 3:
            raise ValueError("COLMAP needs at least 3 usable photos")

        if on_progress:
            on_progress(0, 100)

        database_path = workdir / "database.db"
        max_features = str(int(5000 + quality * 80))

        _run_colmap(
            [
                "feature_extractor",
                "--database_path",
                str(database_path),
                "--image_path",
                str(image_dir),
                "--ImageReader.camera_model",
                "SIMPLE_RADIAL",
                "--ImageReader.single_camera",
                "1",
                "--SiftExtraction.use_gpu",
                "0",
                "--SiftExtraction.max_num_features",
                max_features,
            ],
            workdir,
        )
        if on_progress:
            on_progress(1, 35)

        _run_colmap(
            [
                "exhaustive_matcher",
                "--database_path",
                str(database_path),
                "--SiftMatching.use_gpu",
                "0",
            ],
            workdir,
        )
        if on_progress:
            on_progress(1, 100)

        _run_colmap(
            [
                "mapper",
                "--database_path",
                str(database_path),
                "--image_path",
                str(image_dir),
                "--output_path",
                str(sparse_dir),
                "--Mapper.ba_global_max_num_iterations",
                "40",
            ],
            workdir,
        )
        if on_progress:
            on_progress(3, 100)

        model_dir = sparse_dir / "0"
        if not model_dir.exists():
            raise RuntimeError("COLMAP could not register a reconstruction. Add more overlap and camera movement.")

        ply_path = workdir / "sparse_points.ply"
        _run_colmap(
            [
                "model_converter",
                "--input_path",
                str(model_dir),
                "--output_path",
                str(ply_path),
                "--output_type",
                "PLY",
            ],
            workdir,
        )

        if on_progress:
            on_progress(5, 65)

        ply_bytes = ply_path.read_bytes()
        points, colors = _load_ply_as_arrays(ply_path)

        if len(points) < 10:
            raise RuntimeError("COLMAP reconstructed too few points. Try more photos with stronger side-to-side movement.")

        glb_bytes = _export_glb_points(points, colors)
        obj_bytes = _export_obj_points(points, colors, scan_name)

        if on_progress:
            on_progress(6, 100)

        point_count = int(len(points))
        return {
            "points_3d": points,
            "colors": colors.astype(np.float64) / 255.0,
            "point_count": point_count,
            "obj_bytes": obj_bytes,
            "glb_bytes": glb_bytes,
            "ply_bytes": ply_bytes,
            "quality_score": min(99, int(55 + quality * 0.24 + min(point_count, 60_000) * 0.0003)),
            "coverage_score": min(99, int(40 + image_count * 4 + min(point_count, 80_000) * 0.00025)),
            "texture_score": min(99, int(45 + image_count * 2.8 + detail * 0.25)),
        }
